---
- name: Generate dynamic inventory file
  hosts: localhost
  tasks:
    - name: Fetch the public IP from Terraform output
      command: terraform output -raw web_instance_public_ip
      register: terraform_output

    - name: Create hosts.ini file from template
      template:
        src: ./hosts.ini.j2
        dest: ./hosts.ini
      vars:
        web_instance_public_ip: "{{ terraform_output.stdout }}"
    - name: Debug Terraform output
      debug:
        var: terraform_output.stdout


- name: Configure EC2 instance with Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages including Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Bring up Docker Compose services
      shell: |
        cd /home/ubuntu
        docker-compose up -d
