---
- name: Configure EC2 instance with Docker, Docker Compose, and Node.js
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    - name: Print Docker Compose version
      debug:
        msg: "{{ docker_compose_version.stdout }}"
