---
- name: Configure EC2 instance with Docker, Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

#    - name: Install necessary packages including Docker, Docker Compose
#      apt:
#        name:
#          - docker.io
#          - docker-compose
          # - python3
          # - python3-pip
#        state: present
      # Add notify and handler for restarting Docker service if needed
      # notify:
      #   - Restart Docker service

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Bring up Docker Compose services
      shell: |
        cd /home/ubuntu
        docker-compose up -d
